solution 1
SetMyDream/Spring pull request #1
Opened 2020-10-19 14:07 UTC by SetMyDream

2020-10-19 18:27 UTC, KostiantynVorobiov requested changes

2020-10-19 18:27 UTC, KostiantynVorobiov commented on pom.xml
>  </project>
empty line

2020-10-19 18:27 UTC, KostiantynVorobiov commented on src/main/java/spring/dao/impl/UserDaoImpl.java
> +                    + user.getEmail(), e);
Мне написали что бы я подставил просто user

2020-10-19 18:27 UTC, KostiantynVorobiov commented on src/main/java/spring/service/UserService.java
> +}
empty line

2020-10-19 18:27 UTC, KostiantynVorobiov commented on src/main/java/spring/util/HibernateUtil.java
> +}
Этот клас здесь уже не нужен

2020-10-19 19:08 UTC, SetMyDream commented on src/main/java/spring/util/HibernateUtil.java
> +}
точно, спасибо)\

2020-10-20 06:33 UTC, Sofasmile approved these changes

2020-10-20 06:33 UTC, Sofasmile commented on src/main/java/spring/dao/impl/UserDaoImpl.java
> +                    + user, e);
```suggestion
            throw new DataProcessingException("Can't insert user Entity = "
                    + user, e);
```

2020-10-20 07:35 UTC, merged